- hosts: localhost
  tasks:
    - name: login to docker hub
      command: docker login -u {{ lookup('env', 'DOCKER_USERNAME') }} -p {{ lookup('env', 'DOCKER_PASSWORD') }}
      no_log: true

    - name: create docker image
      command: docker build -t hello:latest .

    - name: create tag to push image onto dockerhub
      command: docker tag hello:latest artef00kt/devops4:latest

    - name: push docker image into dockerhub
      command: docker push artef00kt/devops4:latest